spring.application.name=backend

server.port=8080

spring.config.import=optional:classpath:application-db.properties,optional:classpath:application-secret.properties

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.backend.model